### ISSUE TITLE
Why ROI Pool is used, instead of ROI Align

### ISSUE THREAD

**Issue by XuYunqiu** [jd730/OICR-pytorch#13]
https://github.com/jd730/OICR-pytorch/blob/ab1a0bf00d6bc2acde70bff3edeb303b28d88adc/lib/model/oicr/oicr.py#L86
Why ROI Pool is explicitly used. The ROI Align is implemented in original OICR implementation, I think.

I write a OCIR with Pytorch 1.2, recent days. Batch size of 1 is set in my implementation. It works well with ROI Pool, but it just get about 18 mAP with ROI Align. I am just wondering ROI Align works well in your OICR implementation with batch size of 2?

**Comment by jd730** [comment]
Thank you.  I fixed the code to let an user set pooling mode.
Yes, I also tested on RoI align and it did not work.
When we use RoI align for weakly supervised object detection task, it generates huge performance drops. This was really weird to me since RoI align help to improve the performance on Faster-RCNN.

There are many possibilities, but I guess that since we do not have box-level supervision and RoI align is more minute than RoI pooling, it can have more error while RoI pooling roughly catches the region.

**Comment by XuYunqiu** [comment]
> Thank you. I fixed the code to let an user set pooling mode.
> Yes, I also tested on RoI align and it did not work.
> When we use RoI align for weakly supervised object detection task, it generates huge performance drops. This was really weird to me since RoI align help to improve the performance on Faster-RCNN.
> 
> There are many possibilities, but I guess that since we do not have box-level supervision and RoI align is more minute than RoI pooling, it can have more error while RoI pooling roughly catches the region.

Yes, it seems reasonable. The writer of original OICR implementation also said that many people told him the ROI Align problem.

**Comment by XuYunqiu** [comment]
> Thank you. I fixed the code to let an user set pooling mode.
> Yes, I also tested on RoI align and it did not work.
> When we use RoI align for weakly supervised object detection task, it generates huge performance drops. This was really weird to me since RoI align help to improve the performance on Faster-RCNN.
> 
> There are many possibilities, but I guess that since we do not have box-level supervision and RoI align is more minute than RoI pooling, it can have more error while RoI pooling roughly catches the region.

Yes, it seems reasonable. The writer of original OICR implementation also said that many people told him the ROI Align problem.
