### ISSUE TITLE
question about batchsize

### ISSUE THREAD

**Issue by Feobi1999** [jd730/OICR-pytorch#21]
![0837](https://user-images.githubusercontent.com/35750924/78657108-e194bd80-78fa-11ea-9287-46d001932876.png)
When using two GPUs, bs = 8 will report an error.
May I ask if the actual bs of your code can only be equal to 1 (in the forward and backward propagation)?
And I also notice this **assert** in assign labels.
Thanks

**Comment by jd730** [comment]
Hi @Ferryzhe, both of your questions are related. Since we need to use object proposals such as Selective Search, we require at least 10 GB for each batch. That is why I did not consider more than one batch for each GPU and set the assertion.

Note that the batch size is divided by two on https://github.com/jd730/OICR-pytorch/blob/bcfe9cd2d7ab77fc46bc031da8fd27bd9971d57d/trainval_net.py#L252 and rather the model updates every two forward steps (https://github.com/jd730/OICR-pytorch/blob/bcfe9cd2d7ab77fc46bc031da8fd27bd9971d57d/trainval_net.py#L408).

If you have fancy GPU such as Titan RTX, Quadro 4000/6000/8000, or GV100, you may want to use more batches for each GPU. What you need to do might change code in https://github.com/jd730/OICR-pytorch/blob/master/lib/oicr_layer/layer.py and https://github.com/jd730/OICR-pytorch/blob/master/lib/model/oicr/oicr.py. Or, maybe, the easiest but inefficient way is using a loop when you call OICRLayer.
